---

- hosts: all
  strategy: debug
  roles:
    - common

- hosts: etcd
  strategy: debug
  roles:
    - { role: etcd, when: "ETCD_INSTALL == 'yes'" } 

- hosts: master
  roles:
    - kubectl
    - master

- hosts: minions
  roles:
    - minions

